### ISSUE TITLE
Update for schema 1.1.0

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.metadata#9]

**Comment by ksuderman** [comment]
At least the following changes will be needed.

* [x] Add `licenseDesc` to `ServiceMetadata` and `ServiceMetadataBuilder`
* [x] Add `tagSet` to the `IOSpecification` class.
* [x] Add `tagSet` to the annotations package.

**Comment by keighrim** [comment]
updated in #10
